# Upptime config — https://upptime.js.org/docs/configuration
owner: gabek
repo: gabe-service-status

sites:
  - name: Nextcloud
    url: https://nextcloud.real-ity.com
  - name: social.gabekangas.com
    url: https://social.gabekangas.com/
  - name: The Bat Station
    url: listen.batstationrad.io 
  - name: Owncast Demo Server
    url: https://watch.owncast.online/
  - name: Owncast Nightly
    url: https://nightly.owncast.tv/
  - name: Owncast Directory
    url: https://owncast.directory

status-website:
  name: Service Status
  baseUrl: /gabe-service-status
  introTitle: "Gabe's status page"
  introMessage: Status for misc services.
  navbar:
    - title: Status
      href: /gabe-service-status
